### ISSUE TITLE
Portfolio Suggested Changes

### ISSUE THREAD

**Issue by Sajeelzafar** [RichardChileya/my-portfolio#11]
### Suggested Changes

- The navbar in the desktop version should be anchor tags.
- The margin/padding under the Languages section needs to be adjusted to match the Figma design.
- Ruby on rails button on the mobile screen is larger than the other buttons.
- The text inside the form under the "Contact Me" heading should be given more space.

Other than that we believe, the website seems perfectly done. Especially, the animation of the logo that happens on refreshing.

**Comment by RichardChileya** [comment]
Thank you for your suggestions Sajeel, i have implemented the changes
